---
driver:
  name: vagrant
  customize:
    memory: 9000
    natdnshostresolver1: "on"
    natdnsproxy1: "on"

provisioner:
  name: chef_solo

platforms:

  - name: centos-6.5

suites:
  - name: default

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[ambari::server]
      - recipe[ambari::agent]

    attributes:
         ambari:
            server:
                private_ips: ["10.0.2.15"]
                public_ips: ["10.0.2.15"]
            agent:
                private_ips: ["10.0.2.15"]
                public_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         kagent:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         vagrant: "enabled"
